name: Sync GitHub to Azure DevOps

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "hareesh.gutha9@gmail.com"
          git config --global user.name "hareeshgutha"

      - name: Add Azure DevOps Remote
        run: |
          git remote -v

      - name: Push to Azure DevOps
        run: |
          git push --force azure main  # Change 'main' if using another branch
